# Generated by Django 4.1.3 on 2023-01-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0004_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.EmailField(max_length=30),
        ),
    ]
