# Generated by Django 4.1.3 on 2023-01-19 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0005_alter_mensaje_receptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
