# Generated by Django 4.1.3 on 2023-01-19 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0006_delete_mensaje_post_autor_post_fecha_post_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previewPost',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
