# Generated by Django 4.1.3 on 2023-01-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0007_post_previewpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=60),
        ),
    ]
